.travis.yml
Adds a basic travis.yml
Since we support PHP from 5.2x on, I've PHP support from 5.2 upwards.
=> add the .travis.yml

inc/gui.class.php
Solves #81 
To solve the problem, I consequently did split up the escaping from the translating. The translation now does not use `esc_html__()` no more but `__()`.
During the printing process, instead of trying to translate the variable with `esc_html__()` we just make sure the variable gets escaped.
=> split escaping and translating

inc/gui.class.php
Solves #121 
We did adjust the regex to split the country list string in _antispam_bee.php_ to `/[\s,;]+/` in #86 and changes the placeholder accordingly in #87. The idea was to be able to use comma or semicolon as well to seperate the country codes.
However, we have missed, the rexeg sanitizing the input in _inc/gui.class.php_, which still just allowed A-Z as well as space. This PR extends the allowed characters to comma and semicolon: `/[^A-Z ,;]/`
> I Would expect a comma separated list (like in the placeholder)
It is not exactly the output like the format of the placeholder, you can also use just space or semicolons. But I think its good enough, if we see the placeholder more as a guide, while we actually provide more possibilities to save the data correctly in order to reduce errors. …
=> fix regex for saving country data

inc/gui.class.php
This PR adds Hebrew to the languages and adds a filter, so you can easily add more languages to be selectable and solves #132
I am not quite sure, if we should go and add all possible languages (as a bad UX might outweigh the benefits) or restrict ourselves to the most spoken ones (or the ones, which get requested). Happy to add more languages.
=> add hebrew, make allowed languages filterable (solves #132)

antispam_bee.php
This approach solves #133 by using the `.screen-reader-text` definitions and `tab-index=-1`, so it also disappears from the tabulator usage in my tests. Since we use `aria-hidden="true"`, I think it should be also invisible for screen readers.
=> use screen-reader-css + tabindex=-1

antispam_bee.php, readme.txt
Removes `get_the_title()` to generate the secrets.
Fixes #131.
=> remove usage of get_the_title()

antispam_bee.php
Solves #144.
In #131 we only solved the possibility, the title might change, but actually, the global `$post->ID` can change too if other `WP_Query` run and `wp_reset_postdata` is not executed afterwards.
In order to solve this issue, we hook in the `wp`-action and take the post ID already there. We store it in a variable `$_current_post_id`, which we will use to output the correct secret.
=> Add a reliable post ID as soon as possible (solves #144)

antispam_bee.php
This PR changes the default value of `email_notify` to 0. So by default, we do not send "Comment marked as spam" notifications.
closes #151
=> change the default value for email_notify to 0 (solves #151)

antispam_bee.php
This PR removes the link from the "X Blocked"-Text in the "At a glance"-widget.
Closes #171
=> Remove link from add a glance feature (solves #171)

antispam_bee.php
CSS Hacks are now just „Honeypot“, this way no one should be too much alerted, if they get mail because of blocked spam. closes #192
=> Change „CSS Hack“ label

antispam_bee.php
closes #177 
with gdpr coming up, the comment_author_ip column won't be reliable anymore as more and more people will rightfully start to anonymize this column. even core might follow up on this.
on the other hand the ip address is a very valuable source to determine spam and has been proven effective in preventing spam when stored in the local database.
this approach tries to bring privacy and spam protection together. it stores a salted/hashed version of the ip address of spam comments. if a comment is incoming, we check against this hashed ip.
=> save hashed ip in meta and compare current ip with hashes

CHANGELOG.md, antispam_bee.php, inc/columns.class.php, inc/gui.class.php, readme.txt
This PR closes #232,
If you uninstall, this PR will delete the meta data spam reason and ip hash by default. It provides also an UI and option, so you can prevent this behaviour.
=> delete meta data on uninstall (closes #232)

CHANGELOG.md, antispam_bee.php, readme.txt
We have an option to use comment forms outside of the single view. This option is basically broken since quite a while.
This PR fixes it.
Closes #235 
Closes #128
Basically, what it does:
1. If the option is set, we use a static secret
2. We limit `preg_replace_callback()` no longer to 1
=> make multiple commentforms possible again

tests/Acceptance/Behat/advanced.feature, tests/Acceptance/Behat/bootstrap/PluginContext.php, tests/Acceptance/Behat/env/mu-plugins/change-antispam-bee-salt.php, tests/Acceptance/Behat/filter.feature
closes #245 
During our Pluginkollektiv Hackaton, we realized, that the way, we overwrote the secret in all our scenarios by using the mu-plugin, we basically would blind us to bugs, which would relate to the way we create and check our honeypot.
This PR fixes this issue by introducing a `Given` command in our Acceptance tests:
`Given the secret is fixed`
This command will set an option in the `wp_options` table and the mu-plugin will filter the secret (using the `ab_get_secret_name_for_post` hook) only, if the option is set.
=> Set the secret in the behat test with a `Given` step

antispam_bee.php, tests/Acceptance/Behat/filter.feature
closes #266 
Maps the language code `nds` (Low German) to `de` (German).
Adds a test to check, nds is mapped correctly.
=> Add `nds` language code

.travis.yml, antispam_bee.php, readme.txt
Our tests do also run in PHP nightly. This is now PHP 8. Our dependencies do not support PHP 8 yet, so we disable nightly temporarily.
Additionally, this PR adds WordPress 5.0 and WordPress 5.1 explicitly to the test environment.
closes 276
=> Disable PHP nightly temporarily in tests

CHANGELOG.md, readme.txt
To avoid confusion about _how_ compatible we are with amp, we should adjust the text in the changelog just claiming compatibility with the amp plugin.
For more information see #283 and #242
=> Clarify in changelog: compatible with the amp plugin

antispam_bee.php
Using "new-password" validates as correct HTML5 and is preventing the autocomplete in our tests.
=> Change autocomplete=nope to autocomplete=new-password (fixes #280)

antispam_bee.php
closes #275
The `save_ip_hash()` method is removed and the functionality dehooked.
This PR raises the DB version of ASB, so we delete the data, we do not need anymore.
=> Do not store ip hash

.travis.yml, antispam_bee.php, composer.json
This PR closes #315 
It makes sure our test suite is executed in PHP 7.4
In those tests, it turned out, the plugin activation produced some unexpected output in PHP 7.4
This was due to the fact that the `self::$defaults` where not set when running through the plugin activation. This issue is fixed in the current PR.
Other than that I encountered no problems with PHP 7.4
=> Compatibility with PHP 7.4

antispam_bee.php
Fixes #324 
The action hooks `comment_unapproved_to_spam` and `comment_approved_to_spam` are not used for comment moderation list or comment blocklist (from discussion settings) as the first is setting as "Pending" and the last is sending to "Trash". This means the filter is just used if the spam is marked manually. I think. ;)
=> Add spam reason for manually marked spam

antispam_bee.php
With WordPress 5.5 every comment will have the comment type 'Comment' and therefore or check for an empty comment type fails. This will fix the notification mail accordingly. ( Fixes #343 )
=> Do not check for empty comment type

tests/Acceptance/Behat/filter.feature
With WordPress 5.5 the wording of "Mark as Spam" has changed to "Mark as spam". In our acceptance test, we relied on this wording and as this selector is case sensitive, I switched from the label "Mark as Spam" to the option value "spam", so we can tests WordPress <5.5 as well as >=5.5
fixes #347
=> switch from label 'Mark as Spam' to value 'spam' in behat test

antispam_bee.php, inc/columns.class.php
If there are still some spam comments with reason "Fake IP" the plugin throws a undefined index notice.
This commit re-adds the reason to prevent this.
Fixes #334
=> Add back fake IP reason to prevent notice

antispam_bee.php
The PR adds `!important` to all inline styles of the textarea.
Closes #358
=> Add `!important` to textarea inline styles

.gitignore, .travis.yml, antispam_bee.php, composer.json, tests/Acceptance/Behat/filter.feature
To allow ajaxified comments, this adds a filter to allow ajax calls if necessary
=> Add filter to allow ajax calls

antispam_bee.php
https://antispambee.com does not redirect to https://antispambee.pluginkollektiv.org/de/ (only HTTP works). However, we can directly link to the website as done in other locations already.
=> Replace link in notification

antispam_bee.php
For the Webmention plugin, we introduce multiple new comment types, so we need a way to hook into the `is_ping` check to return `true` on a Webmention ping.
fixes #224
=> make the `ping` detection filterable

.github/workflows/tests.yml
The last workflow runs for #374 failed because of 404 errors during the installation of XVFB. This PR fixes that with adding a `sudo apt-get update` before installing XVFB.
=> Add `apt-get update` before installing xvfb in GitHub Action

.distignore, .gitattributes, .sonarcloud.properties
This PR adds a _.sonarcloud.properties_ file to add some configuration for the SonarCloud [automatic analysis](https://sonarcloud.io/documentation/analysis/automatic-analysis/).
This mode does not support test coverage (obviously, without running tests), but tells the analyzer which files to scan and thus reduces a number of false positives on test files and external resources.
We might go one step further and replace the automatic by manual analysis from CI, if we do want coverage analysis. Requires some tweaks to properly work with multiple test frameworks involved though, so this seems to be a good choice to start for now.
=> introduce SonarCloud analysis

antispam_bee.php
After CodeRisk is acquired and we moved to SonarCloud, this line could be removed safely
Fixes #398
=> Remove Coderisk URL

antispam_bee.php, inc/gui.class.php
Adds the `@change` tags back that were replaced by `2.10.0` and replaces `@change` with `@since`.
=> DocBlock rework

.distignore
Adds the three files to `.distignore` that were included in the 2.10.0 deploy by accident.
=> Add files to .distignore

antispam_bee.php
With WordPress 5.1 a filter `allow_empty_comment` was introduced. If this filter is set to true we need to allow empty comments.
Fixes #421
=> Allow empty comments via core filter

antispam_bee.php, tests/Unit/AntispamBeeTest.php
Code change and description by @stklcode
By default, we only look for the client's IP address in the REMOTE_ADDR header. This can be extended via hook if there is a need to use headers like X-Forwarded-For ("HTTP_X_FORWARDED_FOR") instead.
Headers will be processed in the provided order and return the first valid IP address found.
=> only determine client IP from trusted headers

CHANGELOG.md, antispam_bee.php, readme.txt
=> prepare 2.11.4 release

antispam_bee.php
`Antispam_Bee::_is_ipv6( $ip )` is unused since 2.9.2 (https://github.com/pluginkollektiv/antispam-bee/commit/a14bbe3f5c630a97c541b5f6c93dcf5ca7c6c1e4)
`Antispam_Bee::_reverse_ip( $ip )` is unused since at least 2.6.7 (before the first GitHub commit, did not check the old SVN data)
=> remove unused private methods

CHANGELOG.md, antispam_bee.php, readme.txt
=> Prepare 2.11.6 release

src/Rules/Honeypot.php, tests/Unit/Handlers/CommentTest.php, tests/Unit/Rules/HoneypotTest.php
The script is currently checking if the `REQUEST_URI` is containing `wp-comments-post.php`, the default script to handle the submission of a comment. Some security plugins have options to rename this file to disguise that WordPress is used.
With this fix, the `SCRIPT_NAME` is used instead. Since many security plugins do use rewrite rules, while the `REQUEST_URI` value is changed, the `SCRIPT_NAME` value stays the same. Therefor the condition would still recognize if a comment was submitted.
Original fix by @2ndkauboy in #589, adapted to v3.
=> fix: use SCRIPT_NAME instead of REQUEST_URI to check path (#585)

CHANGELOG.md, antispam_bee.php, readme.txt
=> Update changelog and tested up to version
