pluginkollektiv/antispam-bee

antispam_bee.php

Updated info in plugin header to close #3

Update plugin header

---

antispam_bee.php
inc/columns.class.php
inc/gui.class.php

Updated the plugin text domain to include a dash instead of an underscore.
**Needs review**
Once this is merged, it closes #6.

Dashes for text domain

---

CHANGELOG.md
README.md

think release time investment could be cleaned, too?
will create a CHANGELOG.md later this day

cleaned changelog +support and contribute added

---

CHANGELOG.md

new (not dead) fail2ban links

---

antispam_bee.php

Solves https://github.com/pluginkollektiv/antispam-bee/issues/18

More default Regexes

---

inc/gui.class.php

privacy hints + some more translatable words

---

js/scripts.js
js/scripts.min.js

on mobile devices and 2 cloums display there is some unused space caused by visibility
we can move to "display" and give that space free if we don't need it
#25

move away from visibility and use display

---

inc/gui.class.php

placeholder correction in addition to #86

---

antispam_bee.php
css/dashboard.css
css/styles.css
inc/columns.class.php
inc/gui.class.php
js/dashboard.js

many many changes so i want to pull it now before there are some merge conflicts ;)

english comments

---

inc/gui.class.php

remove typo

---

CHANGELOG.md
antispam_bee.php
inc/gui.class.php

Reintroduce language check

---

css/styles.css

align save button under service links
delete margin bottom
have to go to work so it is now finished ;) will do it in the night
but please try it out

fixes for #92

---

css/styles.css

Reverts pluginkollektiv/antispam-bee#94

Revert "fixes for #92"

---

antispam_bee.php

add a random id

---

antispam_bee.php
tests/Unit/AntispamBeeTest.php
tests/_stubs/includes.php

fix dating-regex

---

inc/gui.class.php

Fixes #119 
I added the `for` attributes, which point to the checkboxes now.

add the for attributes

---

inc/gui.class.php

Fixed text-domain for new string

---

antispam_bee.php

Disable autocomplete on comment input field.

---

inc/gui.class.php

The Language Strings (German, English, French...) are translateable now.

make languages translateable ( solves #138 )

---

antispam_bee.php

To get over with this. This solves #142. I did chose `nope` instead of `off` as suggested here https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion.

replace autocmplete=off with autocmplete=nope (solves #142)

---

antispam_bee.php
readme.txt

Updates the readme and the version of the plugin. solves #141

Update readme and version (#141)

---

.travis.yml
antispam_bee.php

This PR is work in progress. Potentially solves #156 
First step: Update travis.yml :) (~Related: https://github.com/travis-ci/travis-ci/issues/7989~)
2nd step: replace `create_function()`

Updates for 7.2 (solves #156)

---

CHANGELOG.md
antispam_bee.php

as reported you might get a problem on the mobile view (the horizontal scrollbar gets active because of the hidden textarea). padding:0 solves this problem.
closes #168

add padding:0 for hidden textarea (solves #168)

---

CHANGELOG.md
antispam_bee.php

change protocol for stopforumspam.com API requests to HTTPS
add changelog entry
Fixes #175

Switch to HTTPS for stopforumspam.com/ requests

---

antispam_bee.php
inc/gui.class.php
readme.txt

Remove public spam DB due to potential GDPR violation

remove external spam DB closes #180

---

antispam_bee.php

This adds the `antispam_bee_notification_recipients` filter to filter the recipients as discussed in #173 
closes #173

add antispam_bee_notification_recipients filter closes #173

---

inc/gui.class.php

change title "Block comments from specific countries" in ui

---

antispam_bee.php
inc/gui.class.php

 allow more than one language in comments - closes #179

---

CHANGELOG.md
README.md
antispam_bee.php
inc/gui.class.php
readme.txt

- version bump to 2.8.0-beta1
- switch pluginkollektiv.org to https
- update plugin description
- change PayPal-Donationlinks
- add first GDPR stuff

Get README ready for beta1

---

README.md
readme.txt

min version 4.5

---

inc/columns.class.php
inc/gui.class.php
tests/Acceptance/Behat/advanced.feature
tests/Acceptance/Behat/filter.feature
tests/Acceptance/Behat/more.feature
tests/Acceptance/Behat/trackback.feature

A follow up for #211
This PR add test better coverage for our trackbacks, our new filter and prevents, that we would run again into #220

More Behat checks

---

inc/gui.class.php

make links translateable

---

antispam_bee.php

Adds a letter prefix for random comment id/name via a new static property.

prefix letter for secret id/name (closes #242)

---

readme.txt

I've created an updated screenshot and done some minor corrections to the readme.txt.
This PR fixes #204

Update screenshot and readme.txt

---

antispam_bee.php

Extended the regex to match textareas with content.

---

readme.txt

Tested it with Gutenberg and everything seems to work (tested saving of options and submitting a comment loggged in and logged out).

Set tested up to version to 5.0

---

CHANGELOG.md
readme.txt

update changelog and readme for 2.9.1 release

---

CHANGELOG.md
readme.txt

Issue 268 update readme for 291

---

antispam_bee.php
readme.txt

set version to 2.9.1

---

antispam_bee.php

Add data-noptimize attribute to prevent optimization from Autoptimize.

Autoptimize compatibility

---

antispam_bee.php

delete comments AND commentmeta

---

readme.txt

Update readme.txt to reflect the supported WordPress version

---

antispam_bee.php
inc/columns.class.php

Fix the orderby for comment spam reasons

---

inc/gui.class.php

rename black/white list in denied/allowed

---

antispam_bee.php
composer.json
inc/gui.class.php

fixes #304 
This Pull Request removes the Fake IP check.
(Sorry for the delay, like probably everyones, my head is quite elsewhere right now.)

Remove Fake IP check

---

.travis.yml
CHANGELOG.md
antispam_bee.php
readme.txt

Fixes #317 
Fixes #311 
Fixes #293 (documentation-wise)
Changelog added
Sets version to 2.9.2-beta

add changes, set version to 2.9.2-beta

---

CHANGELOG.md
antispam_bee.php
inc/gui.class.php
readme.txt

I updated all links to reference the new documentation and our archive of old Google+ posts.
Fixes #327

Update documentation links

---

antispam_bee.php

Add new spam pattern

---

inc/gui.class.php

This fixes #320 by changing the check description to better match the actual check.
I also updated the German and English documentation accordingly: https://antispambee.pluginkollektiv.org/documentation/#bbcode

Change BBcode check description

---

antispam_bee.php

This fixes #283 
We check if we are in and AMP endpoint and if so, we do not load our JavaScript .

Do not add JavaScript when in AMP endpoint

---

readme.txt

Add contributors

---

CHANGELOG.md
readme.txt

Add Requires PHP header
Add new FAQ entry about form plugins and registration page.
Fix code example
Fix link in FAQ
Add 2.9.3 changelog entries
Remove superfluous "English" header in changelog

Update readme.txt and changelog.md

---

antispam_bee.php

Add comment user agent to regex pattern check (fixes #322)

---

.gitignore
bin/behat.sh
composer.json
composer.lock
package-lock.json
package.json

Non-breaking dev dependency updates.
Also add test directories to .gitignore to keep the workspace clean for local testing.

minor dev-dependency updates

---

.github/workflows/tests.yml
antispam_bee.php
phpcs.xml

Adding checks for global prefixes and text domain values

---

css/dashboard.css
css/styles.css
inc/gui.class.php
js/dashboard.js

Adjust colors to fit 5.7. color palette

---

readme.txt

Adding pfefferle to the contributor list

---

antispam_bee.php

Corrects a few `@change` doc tags for 2.10.0 release.

Fix @change doc tags

---

readme.txt

Add FAQ entry about AJAX comment plugins

---

CHANGELOG.md
antispam_bee.php
readme.txt

Raise "Tested up to" to 5.9, change stable to 2.10.1, add changelog entry
Fixes #429

Prepare 2.11.0

---

inc/gui.class.php

fix: unnecessary translation

---

antispam_bee.php

Fix issue with multiselect

---

CHANGELOG.md
antispam_bee.php
readme.txt

Prepare 2.11.3 release

---

CHANGELOG.md
antispam_bee.php
readme.txt

Prepare 2.11.5 release
